### ISSUE TITLE
兄弟能否留个联系方式

### ISSUE THREAD

**Issue by IamHuskar** [meldonization/depdf#1]
关于pdf文档提取的想讨论一下。就是页面布局分割之类的。

**Comment by meldonization** [comment]
@IamHuskar 

你好，抱歉没及时回复你。如果你还想一起讨论相关的知识点，我这边会建立一个 depdf 讨论微信群，稍后会发出来群二维码，谢谢你的关注。

**Comment by IamHuskar** [comment]
> @IamHuskar
> 
> 你好，抱歉没及时回复你。如果你还想一起讨论相关的知识点，我这边会建立一个 depdf 讨论微信群，稍后会发出来群二维码，谢谢你的关注。

我不知道你这块是 业余做的还是说 工作内容相关。你这个方向上应该还是有很多应用场景的。可以做一些合适的产品。 想探讨一下应用场景。

**Comment by meldonization** [comment]
@IamHuskar  欢迎一起讨论

![钉钉群二维码](https://user-images.githubusercontent.com/1425792/131661158-1ffbb5d3-43a7-4838-8c21-f3c047acfa06.png)
